### ISSUE TITLE
how to hide meeting information

### ISSUE THREAD

**Issue by hakancigci** [ucla/moodle-mod_zoom#173] opened 2020-12-17 19:55 UTC
My Issue is , when meeting load user can click on (i) and all meeting info is displayed , meeting number & password .

question is : how to hide meeting information , or allow users to join meetings through my moodle only .

**Comment by rlorenzo** [comment] 2020-12-18 21:12
@hakancigci That was a feature request from our users to show phone info and that is only possible by showing the invite text. If you want to make it a config please create a pull request with code changes.

**Comment by hakancigci** [comment] 2020-12-18 21:22
I hid it in the module. I saw that it is possible in sdk in Zoom application.

**Comment by rlorenzo** [comment] 2021-03-03 23:52
Duplicate of https://github.com/ucla/moodle-mod_zoom/issues/193

Will be fixed there when that issue is completed

**Closed by rlorenzo** 2021-03-03 23:52 UTC
Labels: help wanted
