### ISSUE TITLE
No reports on Sessions page

### ISSUE THREAD

**Issue by Maniuz** [ucla/moodle-mod_zoom#239] opened 2021-03-27 05:52 UTC
I see the message "No sessions found for this meeting." on the session page of the meetings, for almost all meetings.

I try to use the "Refresh session reports" link inside the "All meetings" page. The link opens the page "mod/zoom/console/get_meeting_report.php?courseid=246&start=2021-03-24&end=2021-03-27" and I can see the title "Get meeting report from Zoom". But I still don't have the reports, again "No sessions found for this meeting." message.

After the refresh session reports I also started the Cron manually.

I updated Zoom plugin to version v3.6 (2021031400) and I'm using Moodle 3.6.3+ (Build: 20190315)

**Comment by lcollong** [comment] 2021-03-27 10:52
In my case, this fix : https://github.com/ucla/moodle-mod_zoom/pull/236 solved the problem

**Comment by rlorenzo** [comment] 2021-04-05 19:44
Merged in https://github.com/ucla/moodle-mod_zoom/pull/236

**Closed by rlorenzo** 2021-04-05 19:44 UTC

**Comment by almadog** [comment] 2021-04-16 11:06
#236 seem to be not accessible. We started getting the same problem around 26 March 2021. Calling the Zoom API direct was returning empty strings for the below data fields and also 0 participants: 
"start_time": "",
"end_time": "",
"duration": "",
"participants": 0,

I have raised it with Zoom Dev support and they have confirmed it is a bug which they a currently looking to fix.

**Comment by jrchamp** [comment] 2021-04-16 20:21
Thank you @almadog for find that and reporting it to Zoom!

Please let us know if you find out that the bug has been resolved.

**Comment by almadog** [comment] 2021-05-14 15:19
They seem to have reverted back and not longer say it is a bug but rather say it is not very well documented in their API documentation...

What seem to happen when I tested and has been confirmed as the expected behaviour by Zoom Dev support is the following:

- if you send GET https://api.zoom.us/v2/metrics/meetings/{meetingid} you will get no starttime, endtime, duration and participants
- if you send GET https://api.zoom.us/v2/metrics/meetings/{meetingid}?type=past you will get starttime, endtime, duration and participants

They have also advised to use to meeting UUID instead of the meetingid but it is worth mentioning that the meeting has different UUID when checked with/without parameter ?type=past

**Comment by jrchamp** [comment] 2021-05-14 16:03
It looks like the code is already using the type=past for all metrics/meetings calls:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/09562dcceadcc28b533e36138c05262c783b392b/classes/webservice.php#L720-L723
